#!/bin/bash

# Available different locations and configurations
# TC_MULTIMEDIJA_NASTAVNICKO (2)
# TC_MULTIMEDIJA_UCENICKO (24)
# PRAKSA_ELEKTROTEHNIKA_UCENICKO
# LAB33_34_NASTAVNICKO (2)
# LAB33_34_UCENICKO (16)
# NOVA_ZGRADA_OSTALO (6)
# NOVA_ZGRADA_UCENICKO (12)
